server:
  port: 8081

spring:
  application:
    name: service-usuarios
  
  datasource:
    url: jdbc:postgresql://neondb_owner:npg_IRns5uLEkmJ6@ep-ancient-glitter-amzfyykl-pooler.c-5.us-east-1.aws.neon.tech/usuarios_db?sslmode=require&channel_binding=require
    username: neondb_owner
    password: ${npg_IRns5uLEkmJ6}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000
  refresh-expiration: 604800000

logging:
  level:
    com.polleria: DEBUG