server.port=8081
spring.application.name=service-usuarios

# URL del frontend permitida para CORS
app.frontend-url=${FRONTEND_URL}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration 
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.soa.soausuarios=DEBUG

# Exponer el endpoint de health
management.endpoints.web.exposure.include=health,info,metrics
management.info.env.enabled=true

# Mostrar detalles del health check (opcional, pero útil)
management.endpoint.health.show-details=always

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.show-actuator=true
# Forzar Swagger a usar JSON y evitar conflictos con XML
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.content-type=application/json
springdoc.writer-with-default-pretty-printer=true